### PR TITLE
Add support for eeschema in KiCad 5

### PR DESCRIPTION
**Pull request by eleanor-clifford**
Thanks for working on this theme, I love it! I've translated the eeschema theme
into the old format, I hope you like it :)

### CODE REVIEW

**Comment by eleanor-clifford** [comment]
@bagnaram any chance you could take a look at this?

**Comment by bagnaram** [comment]
Thank you for the contribution @tim-clifford ! Don't forget to add yourself as a contributor. I will install the V5 of kicad and give it a test.

**Comment by eleanor-clifford** [comment]
No problem :) and good point, I've done that now :tada:

**Comment by bagnaram** [comment]
LGTM
Nice work

**Review by bagnaram — APPROVED** [review]

**Pull request merged**
